site_name: JosÃ© Silva | DevOps Engineer ðŸ”­
theme:
  name: material
  logo: assets/favicon.ico
  favicon: assets/favicon.ico
  custom_dir: docs/overrides
  features:
    - header.autohide
    - announce.dismiss

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - stylesheets/extra.js


nav:
  - Home: index.md
  - Blog TÃ©cnico:
    - Monitoramento:
        - Grafana e Prometheus customizados: blog-tec/monitoring/grafana_prometheus_custom.md

  - Blog AcadÃªmico:
    - O que Ã© DevOps (minha visÃ£o): blog-academic/about_devops/devops-means.md

  - Projetos:
    - CI/CD:
        - Hyundai HPA (AWS): blog-tec/projects/hyundai-hpa.md

